### ISSUE TITLE
怎么让第一次进留言页面不自动弹出键盘啊？

### ISSUE THREAD

**Issue by Uni9k** [zouyaoji/wedding-invitation#21]
怎么让第一次进留言页面不自动弹出键盘啊？
研究好久都没研究出来 谢谢！

**Comment by zouyaoji** [comment]
不自动聚焦就行了吧？

**Comment by Uni9k** [comment]
focus="false" 已经这样设置了 就是第一次进留言页面还是会自动弹。

**Comment by zouyaoji** [comment]
我刚测试了一下 没能重现

**Comment by Uni9k** [comment]
https://tuchuangs.com/imgs/2022/09/03/ed0372edb13fc965.gif

你看 咋回事啊 奇怪了

**Comment by zouyaoji** [comment]
你是不是自己改了啥哦

**Comment by Uni9k** [comment]
我刚还原了message到原始的 还是这样 我等下全部还原试试



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zouyaoji ***@***.***&gt;
发送时间: 2022年9月3日 15:13
收件人: zouyaoji/wedding-invitation ***@***.***&gt;
抄送: Uni9k ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [zouyaoji/wedding-invitation] 怎么让第一次进留言页面不自动弹出键盘啊？ (Issue #21)





 
你是不是自己改了啥哦

**Comment by zouyaoji** [comment]
![录制_2022_09_03_15_14_18_583](https://user-images.githubusercontent.com/24430116/188260305-af72e8cc-075d-408e-9440-8cb5eff46541.gif)

**Comment by Uni9k** [comment]
模拟器不会弹 真机才会弹



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zouyaoji ***@***.***&gt;
发送时间: 2022年9月3日 15:15
收件人: zouyaoji/wedding-invitation ***@***.***&gt;
抄送: Uni9k ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [zouyaoji/wedding-invitation] 怎么让第一次进留言页面不自动弹出键盘啊？ (Issue #21)

**Comment by Uni9k** [comment]
而且真机也是第一次进留言页面会弹 切到其他标签在切留言也不会弹 只有重新进入小程序再去留言页面才会弹



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zouyaoji ***@***.***&gt;
发送时间: 2022年9月3日 15:15
收件人: zouyaoji/wedding-invitation ***@***.***&gt;
抄送: Uni9k ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [zouyaoji/wedding-invitation] 怎么让第一次进留言页面不自动弹出键盘啊？ (Issue #21)

**Comment by zouyaoji** [comment]
我线上那个没问题，应该就是正常的。一套代码的

**Comment by Uni9k** [comment]
我晚上回家删代码用排除试试吧



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zouyaoji ***@***.***&gt;
发送时间: 2022年9月3日 15:19
收件人: zouyaoji/wedding-invitation ***@***.***&gt;
抄送: Uni9k ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [zouyaoji/wedding-invitation] 怎么让第一次进留言页面不自动弹出键盘啊？ (Issue #21)





 
我线上那个没问题，应该就是正常的。一套代码的

**Comment by Uni9k** [comment]
好了 原来是要直接去掉focus，设置false没用 哈哈哈
