### ISSUE TITLE
请教一下你们的视频是怎么做的？

### ISSUE THREAD

**Issue by AlvinZhn** [zouyaoji/wedding-invitation#8]
是否有可以复制的模板？做的挺有意思的，我们也想整一个类似的 😄

**Comment by zouyaoji** [comment]
我都忘记了，反正是一个网站上的模板，花了点小钱。。。我看看还有没有记录，找到了发你，没发就是没找到。。




用最初的心,做永远的事!


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zouyaoji/wedding-invitation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月12日(星期一) 晚上9:43
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zouyaoji/wedding-invitation] 请教一下你们的视频是怎么做的？ (#8)





 
是否有可以复制的模板？做的挺有意思的，我们也想整一个类似的 😄

**Comment by AlvinZhn** [comment]
先谢谢了~！

**Comment by zouyaoji** [comment]
客气了，祝新婚快乐~

还真找到了，婚礼纪里面的，你看看吧
[`https://www.hunliji.com/mv/wedding`](https://www.hunliji.com/mv/wedding)

**Comment by AlvinZhn** [comment]
爱了爱了，谢谢老哥！
